<a href="https://colab.research.google.com/github/amarnath235274856-cmyk/python/blob/july_copy/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas
import pandas as pd

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
# series
s1=pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
s2=pd.Series([1,2,3,4,5],index=["a","b","c","d","e"])
s2

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
s3=pd.Series([1,2,3,4,5],index=["a","b","c","d","e"],dtype="float")
s3

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64

In [ ]:
# creating series of dictonary
dictonary=pd.Series({"amar":1,"selvan":2,"sai":3})
dictonary

amar      1
selvan    2
sai       3
dtype: int64

In [ ]:
# data frames
d1=pd.DataFrame([1,2,3,4,5])
d1

   0
0  1
1  2
2  3
3  4
4  5

In [ ]:
d2=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
d2

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
d3=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=["amar","selvan","sangeetha"])
d3

   amar  selvan  sangeetha
0     1       2          3
1     4       5          6
2     7       8          9

In [ ]:
d4=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=["amar","selvan","sangeetha"],columns=["a","b","c"])
d4

           a  b  c
amar       1  2  3
selvan     4  5  6
sangeetha  7  8  9

In [ ]:
d2=pd.DataFrame(s2)
d2

   0
a  1
b  2
c  3
d  4
e  5

In [ ]:
d2

   0
a  1
b  2
c  3
d  4
e  5

In [ ]:
# creating dsta frames from list of dictonaries
list=[{"amar":90,"sangeetha":35,},{"selvan":100,"sairam":90,"hemu":95},{"Babu":98,"chinapilla":99}]
pd.DataFrame(list,index=["a","b","c"])

   amar  sangeetha  selvan  sairam  hemu  Babu  chinapilla
a  90.0       35.0     NaN     NaN   NaN   NaN         NaN
b   NaN        NaN   100.0    90.0  95.0   NaN         NaN
c   NaN        NaN     NaN     NaN   NaN  98.0        99.0

In [ ]:
# data frame operations
d3

           0  1  2
amar       1  2  3
selvan     4  5  6
sangeetha  7  8  9

In [ ]:
print(d3["amar"])

0    1
1    4
2    7
Name: amar, dtype: int64

In [ ]:
# various dataframe operations
d2

   0
a  1
b  2
c  3
d  4
e  5

In [ ]:
d3

   amar  selvan  sangeetha
0     1       2          3
1     4       5          6
2     7       8          9

In [ ]:
import pandas as pd
d3=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=["x","y","z"],columns=["a","b","c"])
d3

   a  b  c
x  1  2  3
y  4  5  6
z  7  8  9

In [ ]:
print(d3["a"])

x    1
y    4
z    7
Name: a, dtype: int64

In [ ]:
print(d3["c"])

x    3
y    6
z    9
Name: c, dtype: int64

In [ ]:
import pandas as pd
d3=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=["x","y","z"],columns=["a","b","c"])
pop=d3.pop("a")
d3

   b  c
x  2  3
y  5  6
z  8  9

In [ ]:
pop=d3.pop("hemu")
d3

   amar  sangeetha  selvan  sairam
0     1          2       3       4
1     4          5       6       7
2     7          8       9      10

In [ ]:
d3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   c       3 non-null      int64
 1   e       3 non-null      int64
 2   d       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0+ bytes

In [ ]:
d3.describe()

         c    e     d
count  3.0  3.0   3.0
mean   6.0  2.0  10.0
std    3.0  1.0   6.0
min    3.0  1.0   4.0
25%    4.5  1.5   7.0
50%    6.0  2.0  10.0
75%    7.5  2.5  13.0
max    9.0  3.0  16.0

In [ ]:
import pandas as pd
import numpy as np

d4=pd.DataFrame({'abc':np.random.randint(1,5,size=20),'bcd':np.random.randint(1,10,size=20),'cde':np.random.randint(5,10,size=20)})
d4

    abc  bcd  cde
0     2    2    6
1     3    4    7
2     3    4    7
3     4    7    5
4     4    5    8
5     3    7    8
6     1    5    6
7     2    1    6
8     4    9    9
9     2    5    5
10    4    2    9
11    3    4    5
12    1    2    7
13    1    8    7
14    3    5    9
15    4    8    7
16    3    9    8
17    2    6    8
18    1    6    9
19    4    5    7

In [ ]:
d4.head()

   abc  bcd  cde
0    2    2    6
1    3    4    7
2    3    4    7
3    4    7    5
4    4    5    8

In [ ]:
d4.tail()

    abc  bcd  cde
15    4    8    7
16    3    9    8
17    2    6    8
18    1    6    9
19    4    5    7

In [ ]:
d4

    abc  bcd  cde
0     2    2    6
1     3    4    7
2     3    4    7
3     4    7    5
4     4    5    8
5     3    7    8
6     1    5    6
7     2    1    6
8     4    9    9
9     2    5    5
10    4    2    9
11    3    4    5
12    1    2    7
13    1    8    7
14    3    5    9
15    4    8    7
16    3    9    8
17    2    6    8
18    1    6    9
19    4    5    7

In [ ]:
# loc               loc[rowline,columnline]
print(d4.loc[10,'cde'])

9

In [ ]:
print(d4.loc[5,'bcd'])

np.int64(7)

In [ ]:
print(d4.loc[2:4,['abc','bcd','cde']])

   abc  bcd  cde
2    3    4    7
3    4    7    5
4    4    5    8

In [ ]:
d4.loc[[5,6,7],['abc']]

   abc
5    3
6    1
7    2

In [ ]:
print(d4.iloc[4,2])

8

In [ ]:
print(d4.iloc[10,1])

2

In [ ]:
d4.iloc[2:7,[0,2]]

   abc  cde
2    3    7
3    4    5
4    4    8
5    3    8
6    1    6

In [ ]:
d4.iloc[1:11,[0,1,2]]

    abc  bcd  cde
1     3    4    7
2     3    4    7
3     4    7    5
4     4    5    8
5     3    7    8
6     1    5    6
7     2    1    6
8     4    9    9
9     2    5    5
10    4    2    9

In [ ]:
d4.iloc[2:4,[0,1]]

   abc  bcd
2    3    4
3    4    7

In [ ]:
d4.abc

0     2
1     3
2     3
3     4
4     4
5     3
6     1
7     2
8     4
9     2
10    4
11    3
12    1
13    1
14    3
15    4
16    3
17    2
18    1
19    4
Name: abc, dtype: int64

In [ ]:
d4.abc.values    # return in 1d

array([2, 3, 3, 4, 4, 3, 1, 2, 4, 2, 4, 3, 1, 1, 3, 4, 3, 2, 1, 4])

In [ ]:
d4["def"]=d4["abc"]*d4["bcd"]
d4["def"]

0      4
1     12
2     12
3     28
4     20
5     21
6      5
7      2
8     36
9     10
10     8
11    12
12     2
13     8
14    15
15    32
16    27
17    12
18     6
19    20
Name: def, dtype: int64

In [ ]:
# nested list
list_1=[['amar','100','25MC1A6159','5000'],['sangeetha','100','25MC1A6178']]
result=pd.DataFrame(list_1,columns=['name','marks','id_number','pension'])
result

        name marks   id_number pension
0       amar   100  25MC1A6159    5000
1  sangeetha   100  25MC1A6178    None

In [ ]:
list_2=result[result["pension"] >= "4000"]
print(list_2)

   name marks   id_number pension
0  amar   100  25MC1A6159    5000

In [ ]:
result.isnull()

    name  marks  id_number  pension
0  False  False      False    False
1  False  False      False     True

In [ ]:


result.isnull().sum()

name         0
marks        0
id_number    0
pension      1
dtype: int64

In [ ]:
result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       2 non-null      object
 1   marks      2 non-null      object
 2   id_number  2 non-null      object
 3   pension    1 non-null      object
dtypes: object(4)
memory usage: 196.0+ bytes

In [ ]:
result.dropna()

   name marks   id_number pension
0  amar   100  25MC1A6159    5000

In [ ]:
result.fillna(value='4000')

        name marks   id_number pension
0       amar   100  25MC1A6159    5000
1  sangeetha   100  25MC1A6178    4000

In [ ]:
import pandas as pd
data={'name':["amar","sangeetha"],
      'id':[100,100],
      'pension':["5000","4000"]}
df=pd.DataFrame(data)
print(df)

        name   id pension
0       amar  100    5000
1  sangeetha  100    4000

In [ ]:
df=df.drop("id",axis=1)
print(df)

        name pension
0       amar    5000
1  sangeetha    4000

In [ ]:
df=df.drop(0,axis=0)
print(df)

        name pension
1  sangeetha    4000

In [ ]:
import pandas as pd
a=pd.DataFrame({'shoppingapps':['amazon','amazon','meesho','meesho'],'discountpercentage':[10.,20.,60.,40.0],'ratings':[5.,4.8,5,4.0]})
a

  shoppingapps  discountpercentage  ratings
0       amazon                10.0      5.0
1       amazon                20.0      4.8
2       meesho                60.0      5.0
3       meesho                40.0      4.0

In [ ]:
# groupby
a.groupby(['shoppingapps']).mean()

              discountpercentage  ratings
shoppingapps
amazon                      15.0      4.9
meesho                      50.0      4.5

In [ ]:
a.T

                         0       1       2       3
shoppingapps        amazon  amazon  meesho  meesho
discountpercentage    10.0    20.0    60.0    40.0
ratings                5.0     4.8     5.0     4.0

In [ ]:
# get dummies into numerics
import pandas as pd
data={'names':['amarnath','sairam','hemu','anand',],
      'age':[19,20,21,22],
      'village':['enumulavaripalli','enumulavaripalli','enumulavaripalli','enumulavaripalli'],
      'work':['software','software','developer','developer']
}
result=pd.DataFrame(data,columns=['names','age','village','work'])
print(result)

      names  age           village       work
0  amarnath   19  enumulavaripalli   software
1    sairam   20  enumulavaripalli   software
2      hemu   21  enumulavaripalli  developer
3     anand   22  enumulavaripalli  developer

In [ ]:
sample=pd.get_dummies(data['work'],dtype=int)
display(sample)

   developer  software
0          0         1
1          0         1
2          1         0
3          1         0

In [ ]:
sample_1=pd.DataFrame({'names':['amar','sai','hemu','selvaraj'],
                       'age':[19,20,21,22],
                       'work':['btech','keoemployee','btech','9thclass']})
sample_1

      names  age         work
0      amar   19        btech
1       sai   20  keoemployee
2      hemu   21        btech
3  selvaraj   22     9thclass

In [ ]:
sample_2=pd.DataFrame({'names':['charan','kiran','balu','rosaiah maa mama gaaru'],
                       'age':[19,20,21,22],
                       'work':['degree','mba','studier','fieldassitant']})
sample_2

                    names  age           work
0                  charan   19         degree
1                   kiran   20            mba
2                    balu   21        studier
3  rosaiah maa mama gaaru   22  fieldassitant

In [ ]:
pd.concat([sample_1,sample_2],axis=0)

                    names  age           work
0                    amar   19          btech
1                     sai   20    keoemployee
2                    hemu   21          btech
3                selvaraj   22       9thclass
0                  charan   19         degree
1                   kiran   20            mba
2                    balu   21        studier
3  rosaiah maa mama gaaru   22  fieldassitant

In [ ]:
pd.concat([sample_1,sample_2],axis=0,ignore_index=True)

                    names  age           work
0                    amar   19          btech
1                     sai   20    keoemployee
2                    hemu   21          btech
3                selvaraj   22       9thclass
4                  charan   19         degree
5                   kiran   20            mba
6                    balu   21        studier
7  rosaiah maa mama gaaru   22  fieldassitant

In [ ]:
list_1={"names":["charan","kiran","balu","charan","rosaiahmamagaaru"],
          "age":[19,20,21,22,22],
         "work":['degree','mba','degree','studier','fieldassitant']}
list_1

{'names': ['charan', 'kiran', 'balu', 'charan', 'rosaiahmamagaaru'],
 'age': [19, 20, 21, 22, 22],
 'work': ['degree', 'mba', 'degree', 'studier', 'fieldassitant']}

In [ ]:
result=pd.DataFrame(list_1)
result

              names  age           work
0            charan   19         degree
1             kiran   20            mba
2              balu   21         degree
3            charan   22        studier
4  rosaiahmamagaaru   22  fieldassitant

In [ ]:
result=result.drop_duplicates()
print(result)

              names  age           work
0            charan   19         degree
1             kiran   20            mba
2              balu   21         degree
3            charan   22        studier
4  rosaiahmamagaaru   22  fieldassitant

In [ ]:
#apply
def phone(amar):
     return   amar+10
data={
    'a':[10,20,30],
    'b':[40,50,60]}
obj=pd.DataFrame(data)
result1=obj.apply(phone)
result1

    a   b
0  20  50
1  30  60
2  40  70

In [ ]:
# another example for apply function
def car(mine):
  return mine+2
data={
    'amar':[10,20,30],
    'sangeetha':[40,50,60]}
result=pd.DataFrame(data)
result

   amar  sangeetha
0    10         40
1    20         50
2    30         60

In [ ]:
result1=result.apply(car)
result1

   amar  sangeetha
0    12         42
1    22         52
2    32         62

In [ ]:
# creating a sample dataframe with gender
import pandas as pd
data={
    'amar':[10,20,30,10,20],
    'sangeetha':[40,50,60,50,60]}
result=pd.DataFrame(data)
result

   amar  sangeetha
0    10         40
1    20         50
2    30         60
3    10         50
4    20         60

In [ ]:
result_1=pd.Categorical(result['amar'])
print(result_1)

[10, 20, 30, 10, 20]
Categories (3, int64): [10, 20, 30]